/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AavakJavakEntry {
  'id' : string,
  'documentType' : string,
  'entryType' : string,
  'referenceNumber' : string,
  'date' : bigint,
  'createdBy' : string,
  'description' : string,
  'linkedDocId' : [] | [string],
  'constituency' : string,
  'fromTo' : string,
}
export interface AppointmentDateChange {
  'id' : string,
  'constituencyId' : string,
  'createdAt' : bigint,
  'bloId' : string,
  'newDate' : bigint,
  'oldDate' : bigint,
  'reason' : string,
}
export interface AppointmentOrder {
  'id' : string,
  'status' : string,
  'content' : string,
  'constituencyId' : string,
  'createdAt' : bigint,
  'issuedDate' : bigint,
  'bloId' : string,
  'orderNumber' : string,
}
export interface BLO {
  'id' : string,
  'status' : string,
  'appointmentOrderId' : [] | [string],
  'bankAccount' : [] | [string],
  'partNumber' : string,
  'officeAddress' : [] | [string],
  'constituencyId' : string,
  'name' : string,
  'designation' : string,
  'createdAt' : bigint,
  'partName' : string,
  'aadhaar' : [] | [string],
  'email' : [] | [string],
  'updatedAt' : bigint,
  'voterId' : [] | [string],
  'phone' : string,
  'isExcellent' : boolean,
}
export interface BankDetails {
  'ifscCode' : string,
  'bankName' : string,
  'accountNumber' : string,
  'branchName' : string,
}
export interface ConstituencyConfig {
  'id' : string,
  'name' : string,
  'passwordChangedAt' : bigint,
  'loginAttempts' : bigint,
  'isEnabled' : boolean,
  'updatedAt' : bigint,
  'adminPassword' : string,
  'lockedUntil' : [] | [bigint],
}
export interface ExtraPayment {
  'id' : string,
  'status' : string,
  'partNumber' : [] | [string],
  'bloName' : [] | [string],
  'constituencyId' : string,
  'createdAt' : bigint,
  'bloId' : string,
  'amount' : bigint,
  'reason' : string,
}
export interface GPSLocation {
  'lat' : number,
  'lon' : number,
  'pollingStationId' : string,
  'constituencyId' : string,
  'updatedByName' : string,
  'updatedByRole' : string,
  'updatedAt' : bigint,
  'updatedBy' : string,
}
export interface GPSTrackingRecord {
  'assignedBLOName' : [] | [string],
  'pollingStationId' : string,
  'partNumber' : string,
  'constituencyId' : string,
  'partName' : string,
  'gpsUpdatedAt' : [] | [bigint],
  'gpsUpdatedBy' : [] | [string],
  'assignedNodalOfficerName' : [] | [string],
  'assignedSupervisorName' : [] | [string],
  'gpsUpdatedByName' : [] | [string],
  'assignedBLOPhone' : [] | [string],
  'gpsUpdatedByRole' : [] | [string],
  'assignedNodalOfficerId' : [] | [string],
  'assignedBLOId' : [] | [string],
  'location' : string,
  'assignedSupervisorId' : [] | [string],
  'gpsLat' : [] | [number],
  'gpsLon' : [] | [number],
}
export interface HonorariumConfig {
  'constituencyId' : string,
  'currency' : string,
  'baseAmount' : bigint,
  'effectiveFrom' : bigint,
}
export interface HonorariumDistribution {
  'id' : string,
  'constituencyId' : string,
  'quarter' : string,
  'note' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'year' : string,
  'baseAmount' : bigint,
}
export interface HonorariumEligibilityResult {
  'isEligible' : boolean,
  'partNumber' : string,
  'bloName' : string,
  'exclusionReason' : [] | [string],
  'bloId' : string,
  'isManuallyOverridden' : boolean,
}
export interface HonorariumRecord {
  'id' : string,
  'status' : string,
  'constituencyId' : string,
  'approvedAt' : [] | [bigint],
  'approvedBy' : [] | [string],
  'quarter' : string,
  'note' : [] | [string],
  'createdAt' : bigint,
  'bloId' : string,
  'amount' : bigint,
  'paidAt' : [] | [bigint],
  'supervisorId' : [] | [string],
}
export interface HonorariumSummary {
  'total' : bigint,
  'constituencyId' : string,
  'totalPaid' : bigint,
  'totalApproved' : bigint,
  'totalPending' : bigint,
}
export interface NodalOfficer {
  'id' : string,
  'assignedSupervisorIds' : Array<string>,
  'constituencyId' : string,
  'password' : [] | [string],
  'name' : string,
  'designation' : string,
  'createdAt' : bigint,
  'mobileNumber' : [] | [string],
  'isActive' : boolean,
  'loginAttempts' : bigint,
  'updatedAt' : bigint,
  'isLocked' : boolean,
  'phone' : string,
}
export interface Notice {
  'id' : string,
  'noticeType' : string,
  'status' : string,
  'content' : string,
  'noticeNumber' : string,
  'subject' : string,
  'constituencyId' : string,
  'createdAt' : bigint,
  'createdById' : string,
  'clearedByName' : [] | [string],
  'issuedDate' : bigint,
  'clearedById' : [] | [string],
  'updatedAt' : bigint,
  'createdByName' : string,
  'createdByRole' : string,
  'noticeRecipients' : Array<NoticeRecipientStatus>,
  'printHistory' : Array<PrintRecord>,
  'clearedAt' : [] | [bigint],
  'recipientType' : string,
  'recipientId' : string,
  'clearedForHonorarium' : boolean,
  'issuingAuthority' : string,
}
export interface NoticeRecipientStatus {
  'deliveredAt' : [] | [bigint],
  'deliveryStatus' : string,
  'recipientType' : string,
  'recipientId' : string,
  'readAt' : [] | [bigint],
}
export interface NoticeSettings {
  'noticeOfficerDesignation' : string,
  'noticeOfficerName' : string,
  'noticeOfficerTehsil' : string,
  'constituencyId' : string,
  'noticeHeaderEmail' : string,
  'noticeHeaderLine1' : string,
  'noticeHeaderLine2' : string,
  'updatedAt' : bigint,
  'noticeHeaderPhone' : string,
  'noticeOfficerConstituency' : string,
}
export interface OfficialDocumentMeta {
  'id' : string,
  'name' : string,
  'constituency' : string,
  'category' : string,
  'uploadDate' : bigint,
  'uploadedBy' : string,
  'fileKey' : string,
}
export interface OrderSettings {
  'orderOfficerTehsil' : string,
  'constituencyId' : string,
  'orderHeaderPhone' : string,
  'orderOfficerConstituency' : string,
  'updatedAt' : bigint,
  'orderOfficerDesignation' : string,
  'orderOfficerName' : string,
  'orderHeaderEmail' : string,
  'orderHeaderLine1' : string,
  'orderHeaderLine2' : string,
}
export interface PasswordHistoryEntry {
  'action' : string,
  'maskedPassword' : string,
  'changedBy' : string,
  'constituencyId' : string,
  'note' : string,
  'role' : string,
  'timestamp' : bigint,
  'identifier' : string,
}
export interface PollingStation {
  'id' : string,
  'latitude' : [] | [number],
  'partNumber' : string,
  'constituencyId' : string,
  'createdAt' : bigint,
  'partName' : string,
  'updatedAt' : bigint,
  'longitude' : [] | [number],
  'bloId' : [] | [string],
  'location' : string,
  'assignedSupervisorId' : [] | [string],
}
export interface PrintRecord {
  'printedAt' : bigint,
  'printedBy' : string,
  'printedByName' : string,
}
export interface QuarterlyPayment {
  'id' : string,
  'status' : string,
  'constituencyId' : string,
  'quarter' : string,
  'createdAt' : bigint,
  'bloId' : string,
  'amount' : bigint,
  'paidAt' : [] | [bigint],
}
export interface Supervisor {
  'id' : string,
  'constituencyId' : string,
  'password' : [] | [string],
  'name' : string,
  'designation' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'loginAttempts' : bigint,
  'updatedAt' : bigint,
  'assignedStationIds' : Array<string>,
  'isLocked' : boolean,
  'phone' : string,
}
export interface SupervisorHonorariumRequest {
  'id' : string,
  'status' : string,
  'supervisorName' : string,
  'constituencyId' : string,
  'quarter' : string,
  'year' : string,
  'bloIds' : Array<string>,
  'supervisorId' : string,
  'requestedAt' : bigint,
}
export interface _SERVICE {
  'addAavakJavakEntry' : ActorMethod<
    [AavakJavakEntry],
    { 'ok' : AavakJavakEntry } |
      { 'err' : string }
  >,
  'addAppointmentDateChange' : ActorMethod<
    [string, AppointmentDateChange],
    undefined
  >,
  'addConstituency' : ActorMethod<[string, string, string], boolean>,
  'addExtraPayment' : ActorMethod<[string, ExtraPayment], undefined>,
  'addNoticePrintRecord' : ActorMethod<
    [string, string, string, string],
    [] | [Notice]
  >,
  'addOfficialDocMeta' : ActorMethod<
    [OfficialDocumentMeta],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addPollingStation' : ActorMethod<[PollingStation], boolean>,
  'addQuarterlyPayment' : ActorMethod<[string, QuarterlyPayment], undefined>,
  'addSupervisorQuarterlyPayment' : ActorMethod<
    [string, QuarterlyPayment],
    undefined
  >,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'approveHonorarium' : ActorMethod<[string, string], boolean>,
  'bulkSaveBLOs' : ActorMethod<[string, Array<BLO>], bigint>,
  'bulkSaveGPSLocations' : ActorMethod<[string, Array<GPSLocation>], boolean>,
  'bulkSaveNotices' : ActorMethod<[string, Array<Notice>], boolean>,
  'bulkSavePollingStations' : ActorMethod<
    [string, Array<PollingStation>],
    bigint
  >,
  'changeAdminPassword' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
  'changeNodalOfficerPassword' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
  'changeSuperAdminPassword' : ActorMethod<[string, string], boolean>,
  'changeSupervisorPassword' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
  'clearNoticeForHonorarium' : ActorMethod<[string, string, string], boolean>,
  'createAppointmentOrder' : ActorMethod<
    [string, string, string],
    AppointmentOrder
  >,
  'createHonorariumRecord' : ActorMethod<[HonorariumRecord], boolean>,
  'createSupervisorHonorariumRequest' : ActorMethod<
    [SupervisorHonorariumRequest],
    boolean
  >,
  'deleteAavakJavakEntry' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteBLO' : ActorMethod<[string], boolean>,
  'deleteBLOsByConstituency' : ActorMethod<[string], boolean>,
  'deleteNodalOfficer' : ActorMethod<[string, string], boolean>,
  'deleteNotice' : ActorMethod<[string, string], boolean>,
  'deleteOfficialDocMeta' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deletePollingStation' : ActorMethod<[string], boolean>,
  'deleteSupervisor' : ActorMethod<[string, string], boolean>,
  'disableAllConstituencies' : ActorMethod<[], boolean>,
  'enableAllConstituencies' : ActorMethod<[], boolean>,
  'getAavakJavakEntries' : ActorMethod<[string], Array<AavakJavakEntry>>,
  'getAllConstituencyConfigs' : ActorMethod<[], Array<ConstituencyConfig>>,
  'getAllGPSLocations' : ActorMethod<[], Array<GPSLocation>>,
  'getAppointmentDateChanges' : ActorMethod<
    [string],
    Array<AppointmentDateChange>
  >,
  'getAppointmentDateChangesFresh' : ActorMethod<
    [string],
    Array<AppointmentDateChange>
  >,
  'getAppointmentOrders' : ActorMethod<[string], Array<AppointmentOrder>>,
  'getBLOBankDetails' : ActorMethod<[string, string], [] | [BankDetails]>,
  'getBLOs' : ActorMethod<[string], Array<BLO>>,
  'getBLOsBySupervisor' : ActorMethod<[string, string], Array<BLO>>,
  'getConstituencyById' : ActorMethod<[string], [] | [ConstituencyConfig]>,
  'getConstituencyConfig' : ActorMethod<[], [] | [ConstituencyConfig]>,
  /**
   * / Return the full deletion history log
   */
  'getDeleteHistory' : ActorMethod<
    [],
    Array<[string, string, string, string, bigint]>
  >,
  'getEligibleBLOsForHonorarium' : ActorMethod<[string], Array<BLO>>,
  'getExtraPayments' : ActorMethod<[string], Array<ExtraPayment>>,
  'getExtraPaymentsByConstituency' : ActorMethod<[string], Array<ExtraPayment>>,
  'getExtraPaymentsFresh' : ActorMethod<[string], Array<ExtraPayment>>,
  'getGPSLocationsFresh' : ActorMethod<[string], Array<GPSLocation>>,
  'getGPSTrackingInfo' : ActorMethod<[string], Array<GPSTrackingRecord>>,
  'getHonorariumByBLO' : ActorMethod<[string], Array<HonorariumRecord>>,
  'getHonorariumByConstituency' : ActorMethod<
    [string],
    Array<HonorariumRecord>
  >,
  'getHonorariumByConstituencyFresh' : ActorMethod<
    [string],
    Array<HonorariumRecord>
  >,
  'getHonorariumBySupervisor' : ActorMethod<[string], Array<HonorariumRecord>>,
  'getHonorariumConfig' : ActorMethod<[string], [] | [HonorariumConfig]>,
  'getHonorariumDistributions' : ActorMethod<
    [string],
    Array<HonorariumDistribution>
  >,
  'getHonorariumEligibility' : ActorMethod<
    [string],
    Array<HonorariumEligibilityResult>
  >,
  'getHonorariumSummary' : ActorMethod<[string], HonorariumSummary>,
  /**
   * / Returns the NEXT outward counter number for a constituency WITHOUT incrementing.
   * / Use this to preview the reference number before saving the order.
   */
  'getNextOutwardCounter' : ActorMethod<[string], bigint>,
  'getNodalOfficerBLOs' : ActorMethod<[string, string], Array<Supervisor>>,
  'getNodalOfficerSupervisors' : ActorMethod<
    [string, string],
    Array<Supervisor>
  >,
  'getNodalOfficers' : ActorMethod<[string], Array<NodalOfficer>>,
  'getNoticeDeliveryReport' : ActorMethod<
    [string, string],
    Array<NoticeRecipientStatus>
  >,
  'getNoticeSettings' : ActorMethod<[string], [] | [NoticeSettings]>,
  'getNotices' : ActorMethod<[string], Array<Notice>>,
  'getNoticesByCreator' : ActorMethod<[string, string, string], Array<Notice>>,
  'getNoticesByRecipient' : ActorMethod<
    [string, string, string],
    Array<Notice>
  >,
  'getNoticesForDashboard' : ActorMethod<
    [string, string, string],
    Array<Notice>
  >,
  'getNoticesForNodalOfficer' : ActorMethod<
    [string, string, Array<string>, Array<string>],
    Array<Notice>
  >,
  'getNoticesForNodalOfficerFresh' : ActorMethod<
    [string, string, Array<string>, Array<string>],
    Array<Notice>
  >,
  'getNoticesForSupervisor' : ActorMethod<
    [string, string, Array<string>],
    Array<Notice>
  >,
  'getNoticesForSupervisorFresh' : ActorMethod<
    [string, string, Array<string>],
    Array<Notice>
  >,
  'getNoticesFresh' : ActorMethod<[string], Array<Notice>>,
  'getOfficialDocMetas' : ActorMethod<[string], Array<OfficialDocumentMeta>>,
  'getOrderSettings' : ActorMethod<[string], [] | [OrderSettings]>,
  'getPasswordHistory' : ActorMethod<[string], Array<PasswordHistoryEntry>>,
  'getPollingStationGPS' : ActorMethod<
    [string, string],
    [] | [[number, number]]
  >,
  'getPollingStations' : ActorMethod<[string], Array<PollingStation>>,
  'getQuarterlyPayments' : ActorMethod<[string], Array<QuarterlyPayment>>,
  'getSupervisorBankDetails' : ActorMethod<
    [string, string],
    [] | [BankDetails]
  >,
  'getSupervisorHonorariumConfig' : ActorMethod<
    [string],
    [] | [HonorariumConfig]
  >,
  'getSupervisorHonorariumRequests' : ActorMethod<
    [string],
    Array<SupervisorHonorariumRequest>
  >,
  'getSupervisorHonorariumRequestsBySupervisor' : ActorMethod<
    [string],
    Array<SupervisorHonorariumRequest>
  >,
  'getSupervisorQuarterlyPayments' : ActorMethod<
    [string],
    Array<QuarterlyPayment>
  >,
  'getSupervisors' : ActorMethod<[string], Array<Supervisor>>,
  /**
   * / Simple health check — confirms canister is live
   */
  'healthCheck' : ActorMethod<[], string>,
  /**
   * / Increments the outward counter for a constituency and returns the new value.
   * / Call this when the order is actually saved/issued.
   */
  'incrementOutwardCounter' : ActorMethod<[string], bigint>,
  'issueNotice' : ActorMethod<[string, Notice], Notice>,
  'markHonorariumPaid' : ActorMethod<[string], boolean>,
  'nodalOfficerLogin' : ActorMethod<
    [string, string, string],
    [] | [NodalOfficer]
  >,
  /**
   * / Record a deletion event (type, name, deletedBy, reason) with current timestamp
   */
  'recordDeletion' : ActorMethod<[string, string, string, string], undefined>,
  'recordPasswordChange' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
  'restoreHonorariumEligibility' : ActorMethod<
    [string, string, [] | [string]],
    boolean
  >,
  'saveBLO' : ActorMethod<[BLO], boolean>,
  'saveGPSLocation' : ActorMethod<[string, GPSLocation], boolean>,
  'saveNodalOfficer' : ActorMethod<[NodalOfficer], boolean>,
  'saveNotice' : ActorMethod<[string, Notice], boolean>,
  'saveNoticeSettings' : ActorMethod<[NoticeSettings], boolean>,
  'saveOrderSettings' : ActorMethod<[OrderSettings], boolean>,
  'saveSupervisor' : ActorMethod<[Supervisor], boolean>,
  'setBLOBankDetails' : ActorMethod<[string, string, BankDetails], undefined>,
  'setConstituencyAdminPassword' : ActorMethod<
    [string, string, string],
    boolean
  >,
  'setConstituencyEnabled' : ActorMethod<[string, boolean], boolean>,
  'setHonorariumConfig' : ActorMethod<[string, HonorariumConfig], undefined>,
  'setHonorariumDistribution' : ActorMethod<[HonorariumDistribution], boolean>,
  'setHonorariumExcludeOverride' : ActorMethod<
    [string, string, boolean, [] | [string], [] | [string]],
    boolean
  >,
  'setPollingStationGPS' : ActorMethod<
    [string, string, number, number],
    boolean
  >,
  'setSupervisorBankDetails' : ActorMethod<
    [string, string, BankDetails],
    undefined
  >,
  'setSupervisorHonorariumConfig' : ActorMethod<
    [string, HonorariumConfig],
    undefined
  >,
  'superAdminLogin' : ActorMethod<[string], boolean>,
  'supervisorLogin' : ActorMethod<[string, string, string], [] | [Supervisor]>,
  'updateAppointmentOrder' : ActorMethod<[AppointmentOrder], boolean>,
  'updateBLO' : ActorMethod<[BLO], boolean>,
  'updateNodalOfficer' : ActorMethod<[NodalOfficer], boolean>,
  'updateNotice' : ActorMethod<[string, Notice], boolean>,
  'updateNoticeDeliveryStatus' : ActorMethod<
    [string, string, string, string, string],
    boolean
  >,
  'updateNoticeRecipientStatus' : ActorMethod<
    [string, string, string, string],
    boolean
  >,
  'updatePollingStation' : ActorMethod<[PollingStation], boolean>,
  'updateQuarterlyPayment' : ActorMethod<[string, QuarterlyPayment], undefined>,
  'updateSupervisor' : ActorMethod<[Supervisor], boolean>,
  'updateSupervisorQuarterlyPayment' : ActorMethod<
    [string, QuarterlyPayment],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];